# Configuration for GitHub Actions Labeler
# https://github.com/actions/labeler

# Label for LangSmith documentation changes
langsmith:
  - changed-files:
    - any-glob-to-any-file:
      - src/langsmith/**
      - src/langsmith/**/*

# Label for LangGraph documentation changes
langgraph:
  - changed-files:
    - any-glob-to-any-file:
      - src/oss/langgraph/**
      - src/oss/langgraph/**/*

# Label for LangChain documentation changes
langchain:
  - changed-files:
    - any-glob-to-any-file:
      - src/oss/langchain/**
      - src/oss/langchain/**/*
      - src/oss/python/**
      - src/oss/python/**/*
      - src/oss/javascript/**
      - src/oss/javascript/**/*

# Label for OSS documentation changes
oss:
  - changed-files:
    - any-glob-to-any-file:
      - src/oss/**
      - src/oss/**/*

# Label for LangGraph Platform documentation changes
langgraph-platform:
  - changed-files:
    - any-glob-to-any-file:
      - src/langgraph-platform/**
      - src/langgraph-platform/**/*

# Label for Labs documentation changes
labs:
  - changed-files:
    - any-glob-to-any-file:
      - src/labs/**
      - src/labs/**/*

# Label for Python-specific documentation
python:
  - changed-files:
    - any-glob-to-any-file:
      - src/oss/python/**
      - src/oss/python/**/*
      - '**/*.py'

# Label for JavaScript-specific documentation
javascript:
  - changed-files:
    - any-glob-to-any-file:
      - src/oss/javascript/**
      - src/oss/javascript/**/*
      - '**/*.js'
      - '**/*.ts'

# Label for build/CI changes
ci:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/**
      - .github/actions/**
      - Makefile
      - pyproject.toml
      - package.json
      - uv.lock

# Label for documentation infrastructure changes
docs-infra:
  - changed-files:
    - any-glob-to-any-file:
      - pipeline/**
      - pipeline/**/*
      - scripts/**
      - scripts/**/*

# Label for test changes
tests:
  - changed-files:
    - any-glob-to-any-file:
      - tests/**
      - tests/**/*
      - '**/*test*.py'
      - '**/*test*.js'
      - '**/*test*.ts'
