name: LangGraph Platform Documentation
description: Report an issue related to the LangGraph Platform documentation.
title: "[langgraph-platform]: <Please write a comprehensive title>"
labels: [langgraph-platform]

body:
  - type: dropdown
    attributes:
      label: "Type of issue"
      description: "What type of documentation issue are you reporting?"
      options:
        - issue / bug
        - request for content
        - question
        - other
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Language"
      description: "What language is the documentation issue related to?"
      options:
        - Python
        - JavaScript
        - N/A
      default: 0
  - type: textarea
    attributes:
      label: "Description"
      description: >
        Please describe your issue, content request, or question in detail.
        If reporting an issue with current documentation, please include a reference
        to the specific document/code you're referring to.
    validations:
      required: true
